require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.2

ClassLength:
  Max: 120

# If required_ruby_version is increased to 2.3 then this can cop can be enabled and the code updated
# to use the squiggly heredoc feature.
Layout/IndentHeredoc:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/FormatStringToken:
  Enabled: false
