language: ruby
rvm:
  - 2.2.2
  - 2.3.0
  - 2.4.0
  - 2.5.0
script: bundle exec rspec && bundle exec codeclimate-test-reporter
addons:
  code_climate:
    repo_token: 2dfc2d0c4c4bbca83f32cf965e83214d656168982cabf40e5f55855037815157
